package: add parcel to the dev step
This is not working, due to the below exception

```
ReferenceError: regeneratorRuntime is not definedsticky-notes.js:707:66
    value sticky-notes.js:707
    EventHandler sticky-notes.js:1014
    parcelRequire<["sticky-notes.js"]</< sticky-notes.js:1016
    __webpack_require__ sticky-notes.47e9a09f.js:215
    parcelRequire<["sticky-notes.js"]</< sticky-notes.js:184
    __webpack_require__ sticky-notes.47e9a09f.js:215
    parcelRequire<["sticky-notes.js"]</< sticky-notes.js:171
    parcelRequire<["sticky-notes.js"]< sticky-notes.js:173
    newRequire sticky-notes.js:2
    parcelRequire sticky-notes.js:13
    <anonymous> sticky-notes.47e9a09f.js:120
```